export const tagsBlacklist: string[] = [
  "anthro art",
  "anthro artist",
  "anthro cute",
  "anthro furry",
  "anthro nsfw",
  "anthro oc",
  "anthroart",
  "anthroartist",
  "anthrofurry",
  "anthronsfw",
  "anthrooc",
  "art",
  "artist",
  "artwork",
  "cringe",
  "cringeworthy",
  "cute art",
  "cute artwork",
  "cute furry",
  "downvotes galore",
  "drama in comments",
  "drama in the comments",
  "fandom",
  "furries",
  "furry anthro",
  "furry art",
  "furry artist",
  "furry artwork",
  "furry character",
  "furry community",
  "furry cute",
  "furry fandom",
  "furry nsfw",
  "furry oc",
  "furryanthro",
  "furryart",
  "furryartist",
  "furryartwork",
  "furrynsfw",
  "furryoc",
  "image",
  "no tag",
  "not tagged",
  "notag",
  "notags",
  "nsfw anthro",
  "nsfw art",
  "nsfw artist",
  "nsfw artwork",
  "nsfw",
  "nsfwanthro",
  "nsfwart",
  "nsfwartist",
  "nsfwartwork",
  "paywall",
  "rcf community",
  "sfw",
  "solo oc",
  "tag me",
  "tag needed",
  "tag your shit",
  "tagme",
  "upvotes galore",
  "wall of faves"
];
